name: Deploy AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Install Amazon Lambda Tools
      run: dotnet tool install -g Amazon.Lambda.Tools

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_GITHUB_ACTIONS }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_GITHUB_ACTIONS }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy Function
      working-directory: src/DotCruz.Notifications.Delivery.Lambda
      run: |
        dotnet lambda deploy-function notification-delivery-handler-prod
